__start__: program-testowy
	./program-testowy

program-testowy: src/lzespolona.cpp
	g++ -g -Wall -std=c++11 -pedantic -I/home/bk/edu/kpo/zad/z5/lzespolona\
              -o program-testowy src/lzespolona.cpp /home/bk/edu/kpo/zad/z5/test/test-lzespolona.o

clean:
	rm program-testowy
